# -*- coding: utf-8 -*-
"""Forward Chaining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qd22STpC2mWCCQE_WIt7Zjz6-8Fx7NJL

# Forward Chaining
"""

X = "Buaya"
D = "Buas"
E = "Bertaring"
A = "Melompat"
B = "Memakan Serangga"
C = "Ayam"
F = "Hidup di dua alam"
G = "Halal"
H = "Haram"

# D = True; E = True
# A & B = C
# D & E = F
# C = G
# F = H
# H = True

global facts
global is_changed

is_changed = True
facts = [[D,X],[E,X]]

def assert_fact(fact):
    global facts
    global is_changed
    if not fact in facts:
        facts += [fact]
        is_changed = True
        #print (facts)

while is_changed:
    is_changed = False
    for A1 in facts:
        if A1[0] == A and [B,A1[1]] in facts:
            assert_fact([C,A1[1]])
        if A1[0] == D and [E,A1[1]] in facts:
            assert_fact([F,A1[1]])
        if A1[0] == C:
            assert_fact([G,A1[1]])
        if A1[0] == F:
            assert_fact([H,A1[1]])

print(A1)

print(facts)